### ISSUE TITLE
Update actions/cache to 3.0

### ISSUE THREAD

**Issue by MikuAuahDark** [humbletim/setup-vulkan-sdk#11]
This action throws deprecation notice related to `actions/cache` due to Node.js 12 being deprecated.

**Comment by humbletim** [comment]
thanks for the heads up!

**Comment by humbletim** [comment]
cc #12

**Comment by humbletim** [comment]
I believe this has been specifically resolved with #12; please reopen though if other deprecation warnings emerge.
